### ISSUE TITLE
can't support infinit loop

### ISSUE THREAD

**Issue by LaJoie42** [TuringApp/Turing#33]
lors de boucles infinis tel que 
while False==False
le logiciel plante ce qui pose problème au niveau des sauvegardes et de l'utilisation logicielle

y remédier avec une erreur lors de trop grande réitération

**Comment by zdimension** [comment]
chut

**Comment by zdimension** [comment]
after thorough review, it seems that the only way to circumvent this issue would be by running everything in a separate thread, but it requires using Qt signals to do all the IPC shit to make the GUI work

**Comment by zdimension** [comment]
5b863dc
