### ISSUE TITLE
Turing's launch fails on Ubuntu

### ISSUE THREAD

**Issue by projetmbc** [TuringApp/Turing#40]
Hello. Here is what I've tried.

```
> '/home/projetmbc/Téléchargements/turing' 
[20977] Error loading Python lib '/tmp/_MEIe8YWtk/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIe8YWtk/libpython3.6m.so.1.0)
```

**Comment by zdimension** [comment]
The binaries are built using my local WSL system, which runs Ubuntu 18.04 x64. Is your system amd64? Otherwise, you'll need to run from source (should be quick, just follow the instructions on readme.md). Feel free to ask for any info here.

**Comment by projetmbc** [comment]
Here is what I have.

```
> uname -a
Linux cbal-VirtualBox 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by zdimension** [comment]
Indeed, it's weird. The error seems to indicate an incompatibility with the GNU libC, which is typical of an OS version mismatch, but it shouldn't happen here. Which Ubuntu release are you on?

**Comment by projetmbc** [comment]
Here are the infos about my Ubuntu virtual machine.

```
> cat /proc/version
Linux version 4.13.0-38-generic (buildd@lgw01-amd64-027) (gcc version 5.4.0 20160609
(Ubuntu 5.4.0-6ubuntu1~16.04.9)) #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018
```

**Comment by zdimension** [comment]
It's 16.04 and I'm running 18.04, I guess the problem comes from there. I'll upload a new build when I get home, till then I guess your only option is to run from source.

**Comment by projetmbc** [comment]
Don't worry. I will update my Ubuntu.

**Comment by zdimension** [comment]
@projetmbc https://mega.nz/#!nZIRlbTI!fCz38z1H2b2CMb0D-3j6K0goku4s0IWKj4wS9XKsu_Q

Built that one on 14.04, should work now. If you encounter any problems, come on the Gitter, it'll be easier than here
