### ISSUE TITLE
Add Casio, TI and NumWorks converters

### ISSUE THREAD

**Issue by zdimension** [TuringApp/Turing#61]

**Comment by projetmbc** [comment]
You can also add a https://www.numworks.com/fr/ converter.

**Comment by zdimension** [comment]
I don't know those calculators well, only heard about it in the news. Do they use a proprietary algorithm language like Casio and TI?

**Comment by projetmbc** [comment]
No they use a Python like syntax.

**Comment by zdimension** [comment]
98c4236 + d3a0a45

**Comment by zdimension** [comment]
Issue moved to #62, #63 and #64.
